name: Reporte de incidente
description: Registrar un incidente técnico del proyecto Angular
title: "INC-___ : "
labels: ["tipo: bug", "estado: nuevo"]
body:
  - type: input
    id: codigo
    attributes:
      label: Código del incidente
      placeholder: INC-001
    validations:
      required: true
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      description: Explique qué problema ocurre.
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      placeholder: |
        1. Ir a...
        2. Hacer clic en...
        3. Observar...
    validations:
      required: true
  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      options:
        - Baja
        - Media
        - Alta
        - Crítica
    validations:
      required: true
  - type: dropdown
    id: modulo
    attributes:
      label: Módulo afectado
      options:
        - Dashboard
        - Formulario
        - Lista
        - Detalle
        - Servicio
        - Rutas
        - Interfaz
    validations:
      required: true
  - type: textarea
    id: criterio_cierre
    attributes:
      label: Criterio de cierre
      description: Indique cómo se verificará que el incidente fue solucionado.
    validations:
      required: true
